image:
  - adoptopenjdk/openjdk11:alpine-jre
  - maven:3.6.0-jdk-13-alpine

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: mvn package

test:
  stage: test
  script: mvn test

deploy:
  stage: deploy
  image: ruby:latest
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api_key=$HEROKU_API_KEY