version: '3'

services:
  tinder-app:
    container_name: tinder-app
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - PORT=8080
    image: 'tinder-app'
    ports:
      - "8080:8080"